[package]
name = "docbuf-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://docbuf.com"
description = "DocBuf core utilities"
readme = "../README.md"
repository = "https://github.com/docbuf/docbuf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = { version = "0.13.0", features = [] }
nom = { version = "7.1.3", features = ["alloc"] }
regex = "1.10.3"
thiserror = "1.0.56"
