[package]
name = "docbuf-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = []

[dependencies]
docbuf-derive = { path = "../derive" }
proc-macro-error = "1.0.4"
